### ISSUE TITLE
Modelo de dados

### ISSUE THREAD

**Issue by hilam** [PUG-PB-Traducao/datarepo#1]
Definição do modelo de dados conforme as necessidades funcionais da webapp.

**Comment by hilam** [comment]
**Requisitos funcionais da webapp**

1) Submissão de links (anônimos ou registrados)

2) Alerta de submissão aos contribuidores que se registrarem (OAuth Github)

3) Notificação ao submetedor quando o artigo estiver traduzido

4) Votação de artigos para priorização (usuários registrados)

5) Aprovação para ir ao site de tradução (curadores do site)

**Comment by hilam** [comment]
Após a reunião, ficou como tarefa pra cada um fazer, até sexta-feira (10/01/2020) um modelo entidade-relacionamento e estudar SQLAlchemy para codificar o modelo.

**Comment by xarpy** [comment]
Bom dia pessoal, segue a documentação do [https://docs.sqlalchemy.org/en/13/](SQLAlchemy), para podermos trabalhar com isso, A motivo de sugestão, estou inserindo 2 novos links, para contextualizar como iremos brincar com esse ER e script em python para inserir no framework FastAPI. Segue os links:

- Noticia do suporte a ORM[https://www.reddit.com/r/Python/comments/c6jk8r/fastapi_is_now_fully_compatible_with_all_orms/](link)
- Sugestão de como usar o ORM no framework [https://frankie567.github.io/fastapi-users/configuration/databases/sqlalchemy/](link)
- Lib que trabalha facilitando o meio de campo[https://github.com/mfreeborn/fastapi-sqlalchemy](link)

**Comment by xarpy** [comment]
@hilam, por favor ao fim do projeto ou no inicio, se for possível, gostaria de adicionar como tópico a criação de um [**scaffold**](https://pt.stackoverflow.com/questions/119731/o-que-%C3%A9-scaffold) de nossa API e WebAPP, utilizando o [cookiecutter (https://cookiecutter.readthedocs.io/en/latest/index.html).

Isso colabora para que no futuro possamos compartilhar do nosso projeto com outros times, permitindo a implementação mais rápida, já que teremos um template pronto e usável para nosso projeto.Tanto que pode virar uma issue mais tarde, se o grupo aceitar a sugestão!

Grande abraço a todos e bons estudos pessoal!

**Comment by hilam** [comment]
A ideia é ótima. Sinta-se à vontade pra criar uma issue com esse objetivo, para não esquecermos.

**Comment by hilam** [comment]
### Resumo da reunião de 13/01/2020

* Definimos o fluxo de colaboração: 
  1) fork do repositório para o seu usuário
  2) clone do seu fork
  3) criação de branch local
  4) subir a branch para o seu fork
  5) PR da branch para o repositório principal

* Entidades do modelo: Roles, Users, Permissions, Posts
* O @xarpy vai submeter um PR pra servir de guia para as sugestões da equipe
* Demais integrantes continuam a estudar SQLAlchemy e as bibliotecas [fastapi-users](https://frankie567.github.io/fastapi-users/) e [fastapi-sqlalchemy](https://github.com/mfreeborn/fastapi-sqlalchemy)

**Comment by hilam** [comment]
### Resumo da reunião de 24/01/2020

* revisão do modelo
* @xarpy vai atualizar o PR
* @hilam vai escrever nos outros README para esclarecer mais detalhes do projeto como um todo
* Demais integrantes se ambientar nos processos de PR
* Demais integrantes continuam a estudar SQLAlchemy e as bibliotecas fastapi-users e fastapi-sqlalchemy
